### ISSUE TITLE
Create new endpoints

### ISSUE THREAD

**Issue by viraphilavong** [TechEveryday/dotnet_api#5]
Create the following endpoints

- POST /weatherforecast
-- to create a new weather forecast for a city
-- should take in a argument/parameter of type CityForecast
-- [Example POST and GET](https://www.pragimtech.com/blog/blazor/post-in-aspnet-core-rest-api/)

- GET /weatherforecast/{city}
-- to get the current forecast for a city

- PATCH /weatherforecase/{city}
-- update the forecast for a city
-- should take in an argument/parameter of type CityForecast
-- [Example PATCH](https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-7.0#action-method-code)

**Comment by shortymai** [comment]
Get, post and patch endpoints created
